#ifndef CODE_H
#define CODE_H

#include "common.h"

namespace aria {
enum class opCode : uint8_t
{
    LOAD_CONST,
    LOAD_NIL,
    LOAD_TRUE,
    LOAD_FALSE,
    POP,
    POP_N,
    LOAD_LOCAL,
    STORE_LOCAL,
    LOAD_UPVALUE,
    STORE_UPVALUE,
    CLOSE_UPVALUE,
    DEF_GLOBAL,
    LOAD_GLOBAL,
    STORE_GLOBAL,
    LOAD_PROPERTY,
    STORE_PROPERTY,
    LOAD_SUBSCR,
    STORE_SUBSCR,
    EQUAL,
    NOT_EQUAL,
    GREATER,
    GREATER_EQUAL,
    LESS,
    LESS_EQUAL,
    ADD,
    SUBTRACT,
    MULTIPLY,
    DIVIDE,
    MOD,
    NOT,
    NEGATE,
    INC,
    DEC,
    PRINT,
    NOP,
    JUMP_FWD,
    JUMP_BWD,
    JUMP_TRUE,
    JUMP_TRUE_NOPOP,
    JUMP_FALSE,
    JUMP_FALSE_NOPOP,
    CALL,
    CLOSURE,
    MAKE_CLASS,
    INHERIT,
    MAKE_METHOD,
    MAKE_INIT_METHOD,
    INVOKE_METHOD,
    LOAD_SUPER_METHOD,
    MAKE_LIST,
    MAKE_MAP,
    IMPORT,
    GET_ITER,
    ITER_HAS_NEXT,
    ITER_GET_NEXT,
    BEGIN_TRY,
    END_TRY,
    THROW,
    RETURN,
};
}

#endif // CODE_H