#ifndef ARIA_ARIAAPI_H
#define ARIA_ARIAAPI_H

#include "aria.h"
#include "common.h"
#include "memory/gc.h"
#include "object/funDef.h"
#include "object/objBoundMethod.h"
#include "object/objClass.h"
#include "object/objFunction.h"
#include "object/objInstance.h"
#include "object/objIterator.h"
#include "object/objList.h"
#include "object/objMap.h"
#include "object/objModule.h"
#include "object/objNativeFn.h"
#include "object/objString.h"
#include "object/objUpvalue.h"
#include "object/object.h"
#include "runtime/native.h"
#include "runtime/vm.h"
#include "sys.h"
#include "util/nativeUtil.h"
#include "value/value.h"
#include "value/valueArray.h"
#include "value/valueHashTable.h"
#include "value/valueStack.h"

#endif //ARIA_ARIAAPI_H
